### ISSUE TITLE
Snippet idea...

### ISSUE THREAD

**Issue by DavidAnderson684** [affiliatewp/library#1]
Cause a WooCommerce coupon to only be valid if the visitor came via an affiliate (or, via a specific affiliate).

Use case: allow affiliates to advertise coupons, without those coupons then being open to being shared on coupon sites and getting discounts for people they weren't intended for.

**Comment by sumobi** [comment]
@DavidAnderson684 great idea! I'll see what I can do

**Comment by sumobi** [comment]
@DavidAnderson684 https://github.com/affiliatewp/library/blob/master/misc/block-coupon-if-not-referred.php

**Comment by DavidAnderson684** [comment]
Thanks very much!

David
