### ISSUE TITLE
Jetpack sharing issue

### ISSUE THREAD

**Issue by luqmansungkar** [affiliatewp/library#2]
Hi, I'm using code snippet from append-affiliate-id-to-jetpack-sharing-links.php to integrate jetpack sharing button with user affiliate link. This code work fine with twitter share, but when I try to share using facebook, the affiliate ID is not appended to the shared links.

Any idea?
Thank you :)

**Comment by sumobi** [comment]
@luqmansungkar Could you please contact us from our support page so we can assist? http://affiliatewp.com/support/
